### ISSUE TITLE
Fails to successfully start the AppImage

### ISSUE THREAD

**Issue by Victor239** [ActivityWatch/activitywatch#1105]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS name and version**: Kubuntu 24.10
- **ActivityWatch version**: [v0.13.2](https://github.com/ActivityWatch/activitywatch/releases/tag/v0.13.2)

## Describe the bug
When trying to launch the AppImage I get the following error message:

```
2024-10-16 16:30:08 [INFO ]: Started aw-qt...  (aw_qt.main:53)
2024-10-16 16:30:08 [WARNING]: Found matching file but was not executable: /tmp/.mount_activiaueqW2/aw-qt.desktop  (aw_qt.manager:64)
2024-10-16 16:30:08 [INFO ]: Found 8 bundled modules  (aw_qt.manager:85)
2024-10-16 16:30:08 [INFO ]: Found 1 system modules  (aw_qt.manager:119)
2024-10-16 16:30:08 [INFO ]: Starting module aw-server  (aw_qt.manager:148)
2024-10-16 16:30:08 [INFO ]: Starting module aw-awatcher  (aw_qt.manager:148)
2024-10-16 16:30:08 [INFO ]: Creating trayicon...  (aw_qt.trayicon:208)
/tmp/.mount_activiaueqW2/aw-qt: symbol lookup error: /tmp/.mount_activiaueqW2/libQt6WaylandClient.so.6: undefined symbol: wl_proxy_marshal_flags
boss@boss-fwk13-7040:~$ Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py", line 117, in <module>
  File "PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py", line 28, in _pyi_rthook
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "pkgutil.py", line 138, in <module>
  File "functools.py", line 811, in singledispatch
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1423, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1397, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1378, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 423, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 716, in spec_from_file_location
  File "<frozen zipimport>", line 191, in get_filename
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 536, in _get_data
OSError: [Errno 107] Transport endpoint is not connected: '/tmp/.mount_activiaueqW2/aw-server/base_library.zip'
[82492] Failed to execute script 'pyi_rth_pkgutil' due to unhandled exception!
Error: Failed to create bucket aw-watcher-afk_boss-fwk13-7040

Caused by:
    0: error sending request for url (http://127.0.0.1:5600//api/0/buckets/aw-watcher-afk_boss-fwk13-7040): error trying to connect: tcp connect error: Connection refused (os error 111)
    1: error trying to connect: tcp connect error: Connection refused (os error 111)
    2: tcp connect error: Connection refused (os error 111)
    3: Connection refused (os error 111)
```

## To Reproduce
1. Launch AppImage from the command line 
2. See error

## Expected behavior
No error

**Comment by tobixen** [comment]
I have the same.  Installed the official activitywatch-bin-0.13.2-1 from AUR, starting `aw-qt`, I get an error ``/opt/activitywatch/libQt6WaylandClient.so.6: undefined symbol: wl_proxy_marshal_flags`.  Full logs below.  The interesting part is that things seems to work when compiling it manually through python virtualenv from the main branch.  Perhaps this issue has been fixed, but not released yet?

```
2025-05-14 07:15:00 [INFO ]: Started aw-qt...  (aw_qt.main:53)
2025-05-14 07:15:00 [WARNING]: Found matching file but was not executable: /opt/activitywatch/aw-server-rust/aw-server.service  (aw_qt.manager:64)
2025-05-14 07:15:00 [WARNING]: Found matching file but was not executable: /opt/activitywatch/aw-qt.desktop  (aw_qt.manager:64)
2025-05-14 07:15:00 [INFO ]: Found 7 bundled modules  (aw_qt.manager:85)
2025-05-14 07:15:00 [INFO ]: Found 0 system modules  (aw_qt.manager:119)
2025-05-14 07:15:00 [INFO ]: Starting module aw-server  (aw_qt.manager:148)
2025-05-14 07:15:00 [INFO ]: Starting module aw-watcher-afk  (aw_qt.manager:148)
2025-05-14 07:15:00 [INFO ]: Starting module aw-watcher-window  (aw_qt.manager:148)
2025-05-14 07:15:00 [INFO ]: Creating trayicon...  (aw_qt.trayicon:208)
aw-qt: symbol lookup error: /opt/activitywatch/libQt6WaylandClient.so.6: undefined symbol: wl_proxy_marshal_flags

2025-05-14 07:15:00 [INFO ]: aw-watcher-afk started  (aw_watcher_afk.afk:62)
2025-05-14 07:15:00 [INFO ]: aw-watcher-window started  (aw_watcher_window.main:70)
2025-05-14 07:15:00 [INFO ]: Using storage method: peewee  (aw_server.main:33)
2025-05-14 07:15:00 [INFO ]: Starting up...  (aw_server.main:41)
2025-05-14 07:15:00 [INFO ]: Using database file: /home/tobias/.local/share/activitywatch/aw-server/peewee-sqlite.v2.db  (aw_datastore.storages.peewee:150)
 * Serving Flask app 'aw-server'
 * Debug mode: off
2025-05-14 07:15:00 [INFO ]: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:5600  (werkzeug:187)
2025-05-14 07:15:00 [INFO ]: Press CTRL+C to quit  (werkzeug:187)
2025-05-14 07:15:01 [INFO ]: afkwatcher stopped because parent process died  (aw_watcher_afk.afk:82)
2025-05-14 07:15:01 [INFO ]: Connection to aw-server established by aw-watcher-afk  (aw_client.client:447)
2025-05-14 07:15:01 [INFO ]: window-watcher stopped because parent process died  (aw_watcher_window.main:110)
2025-05-14 07:15:01 [INFO ]: Connection to aw-server established by aw-watcher-window  (aw_client.client:447)
```

**Comment by tobixen** [comment]
Here is the corresponding log when starting `aw-qt` from venv and latest git:

```
$ ./venv/bin/aw-qt 
2025-05-14 07:22:03 [INFO ]: Started aw-qt...  (aw_qt.main:53)
2025-05-14 07:22:03 [WARNING]: Found matching file but was not executable: /home/tobias/activitywatch/aw-qt/aw-qt.spec  (aw_qt.manager:64)
2025-05-14 07:22:03 [INFO ]: Found 0 bundled modules  (aw_qt.manager:85)
2025-05-14 07:22:03 [INFO ]: Found 3 system modules  (aw_qt.manager:119)
2025-05-14 07:22:03 [INFO ]: Starting module aw-server  (aw_qt.manager:148)
2025-05-14 07:22:03 [INFO ]: Starting module aw-watcher-window  (aw_qt.manager:148)
2025-05-14 07:22:03 [INFO ]: Starting module aw-watcher-afk  (aw_qt.manager:148)
2025-05-14 07:22:03 [INFO ]: Creating trayicon...  (aw_qt.trayicon:208)
2025-05-14 07:22:03 [INFO ]: Initialized aw-qt and trayicon successfully  (aw_qt.trayicon:264)
2025-05-14 07:22:04 [INFO ]: aw-watcher-window started  (aw_watcher_window.main:71)
2025-05-14 07:22:04 [INFO ]: aw-watcher-afk started  (aw_watcher_afk.afk:62)
2025-05-14 07:22:04 [INFO ]: Using storage method: peewee  (aw_server.main:33)
2025-05-14 07:22:04 [INFO ]: Starting up...  (aw_server.main:41)
2025-05-14 07:22:04 [INFO ]: Using database file: /home/tobias/.local/share/activitywatch/aw-server/peewee-sqlite.v2.db  (aw_datastore.storages.peewee:150)
 * Serving Flask app 'aw-server'
 * Debug mode: off
2025-05-14 07:22:04 [INFO ]: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:5600  (werkzeug:187)
2025-05-14 07:22:04 [INFO ]: Press CTRL+C to quit  (werkzeug:187)
2025-05-14 07:22:04 [INFO ]: Connection to aw-server established by aw-watcher-window  (aw_client.client:461)
2025-05-14 07:22:04 [INFO ]: Connection to aw-server established by aw-watcher-afk  (aw_client.client:461)
2025-05-14 07:22:11 [ERROR]: Unhandled exception in listener callback  (pynput.keyboard.Listener:233)
Traceback (most recent call last):
  File "/home/tobias/activitywatch/venv/lib/python3.13/site-packages/pynput/_util/__init__.py", line 229, in inner
    return f(self, *args, **kwargs)
  File "/home/tobias/activitywatch/venv/lib/python3.13/site-packages/pynput/_util/xorg.py", line 470, in _handler
    self._handle(self._display_stop, event)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '_thread._ThreadHandle' object is not callable
2025-05-14 07:22:11 [ERROR]: Unhandled exception in listener callback  (pynput.mouse.Listener:233)
Traceback (most recent call last):
  File "/home/tobias/activitywatch/venv/lib/python3.13/site-packages/pynput/_util/__init__.py", line 229, in inner
    return f(self, *args, **kwargs)
  File "/home/tobias/activitywatch/venv/lib/python3.13/site-packages/pynput/_util/xorg.py", line 470, in _handler
    self._handle(self._display_stop, event)
    ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '_thread._ThreadHandle' object is not callable
2025-05-14 07:22:12 [INFO ]: Received heartbeat after pulse window, inserting as new event. (bucket: aw-watcher-window_archlinux)  (aw_server.api:317)
```

(There is a problem there also, but that should probably be raised in another issue)

**Comment by cweiske** [comment]
The "undefined symbol: wl_proxy_marshal_flags" was already reported in #939 and #1077.

**Comment by Zach-Pouska** [comment]
On arch linux with KDE plasma (wayland) - using a freshly installed AUR package `activitywatch-bin` I'm seeing the same 
```2026-03-13 16:18:48 [WARNING]: Found matching file but was not executable: /opt/activitywatch/aw-qt.desktop  (aw_qt.manager:64)
2026-03-13 16:18:48 [WARNING]: Found matching file but was not executable: /opt/activitywatch/aw-server-rust/aw-server.service  (aw_qt.manager:64)
```
I tried doing a simple `chmod +x` on the two files for fun to see if it would do anything, and that did get rid of the second line for the aw-server-rust, but the qw-qt.desktop error persists after that. 

The program technically runs for me but I'm not seeing any windows tracked asides from aw-qt in the menu. 

<img width="1172" height="985" alt="Image" src="https://github.com/user-attachments/assets/55bbd83b-dd51-47d8-8f6b-e3d682aa8b04" /> 


Currently trying to start up aw-qt looks like this for me: 
```
2026-03-13 16:27:32 [INFO ]: Started aw-qt...  (aw_qt.main:53)
2026-03-13 16:27:32 [WARNING]: Found matching file but was not executable: /opt/activitywatch/aw-qt.desktop  (aw_qt.manager:64)
2026-03-13 16:27:32 [INFO ]: Found 8 bundled modules  (aw_qt.manager:85)
2026-03-13 16:27:32 [INFO ]: Found 0 system modules  (aw_qt.manager:119)
2026-03-13 16:27:32 [INFO ]: Starting module aw-server  (aw_qt.manager:148)
2026-03-13 16:27:32 [INFO ]: Starting module aw-watcher-window  (aw_qt.manager:148)
2026-03-13 16:27:32 [INFO ]: Starting module aw-watcher-afk  (aw_qt.manager:148)
2026-03-13 16:27:32 [INFO ]: Creating trayicon...  (aw_qt.trayicon:208)
2026-03-13 16:27:32 [INFO ]: Initialized aw-qt and trayicon successfully  (aw_qt.trayicon:264)
2026-03-13 16:27:32 [INFO ]: aw-watcher-afk started  (aw_watcher_afk.afk:62)
2026-03-13 16:27:32 [INFO ]: aw-watcher-window started  (aw_watcher_window.main:70)
2026-03-13 16:27:32 [INFO ]: Using storage method: peewee  (aw_server.main:33)
2026-03-13 16:27:32 [INFO ]: Starting up...  (aw_server.main:41)
2026-03-13 16:27:32 [INFO ]: Using database file: /home/zach/.local/share/activitywatch/aw-server/peewee-sqlite.v2.db  (aw_datastore.storages.peewee:150)
 * Serving Flask app 'aw-server'
 * Debug mode: off
2026-03-13 16:27:32 [INFO ]: WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://localhost:5600  (werkzeug:187)
2026-03-13 16:27:32 [INFO ]: Press CTRL+C to quit  (werkzeug:187)
2026-03-13 16:27:33 [INFO ]: Connection to aw-server established by aw-watcher-afk  (aw_client.client:447)
2026-03-13 16:27:33 [INFO ]: Connection to aw-server established by aw-watcher-window  (aw_client.client:447)

2026-03-13 16:27:33 [WARNING]: Code made an unclear branch  (aw_watcher_window.xlib:121)

2026-03-13 16:27:33 [WARNING]: Code made an unclear branch  (aw_watcher_window.xlib:121)
2026-03-13 16:27:33 [WARNING]: I don't think this case will ever happen, but not sure so leaving this message here just in case.  (aw_watcher_window.xlib:82)
2026-03-13 16:27:33 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:133)
Traceback (most recent call last):
  File "aw_watcher_window/main.py", line 115, in heartbeat_loop
  File "aw_watcher_window/lib.py", line 64, in get_current_window
  File "aw_watcher_window/lib.py", line 17, in get_current_window_linux
  File "aw_watcher_window/xlib.py", line 85, in get_window_name
AttributeError: 'NoneType' object has no attribute 'decode'

2026-03-13 16:27:34 [WARNING]: Code made an unclear branch  (aw_watcher_window.xlib:121)

2026-03-13 16:27:34 [WARNING]: Code made an unclear branch  (aw_watcher_window.xlib:121)
2026-03-13 16:27:34 [WARNING]: I don't think this case will ever happen, but not sure so leaving this message here just in case.  (aw_watcher_window.xlib:82)
2026-03-13 16:27:34 [ERROR]: Exception thrown while trying to get active window  (aw_watcher_window.main:133)
Traceback (most recent call last):
  File "aw_watcher_window/main.py", line 115, in heartbeat_loop
  File "aw_watcher_window/lib.py", line 64, in get_current_window
  File "aw_watcher_window/lib.py", line 17, in get_current_window_linux
  File "aw_watcher_window/xlib.py", line 85, in get_window_name
AttributeError: 'NoneType' object has no attribute 'decode'
```

**Comment by tobixen** [comment]
I've been running a working setup with activitywatch for quite a while, but using systemd instead of aw-qt.

**Comment by nerumo** [comment]
> I've been running a working setup with activitywatch for quite a while, but using systemd instead of aw-qt.

That's interesting. Would you mind sharing your Unit files?

**Comment by tobixen** [comment]
The contents of the systemd unit files are already out on GitHub, so I will not copy-paste it here.

The `aw-server` and `aw-server-rust`  Makefiles come with an `install` target that will copy out the service file (just run `git clone https://github.com/ActivityWatch/aw-server-rust.git ; cd aw-server ; make install`). (I'm not sure if aw-server is officially deprecated for aw-server-rust, but apparently the latter is the future and the former is the past).

The unit should be run in the user domain, so enable with `systemctl --user enable aw-server` after installing the server (that's correct, the unit name does not follow the repo name).

I'm using `aw-watcher-window-wayland` - it does not come with systemd support by default.  I've added a pull request for it, https://github.com/ActivityWatch/aw-watcher-window-wayland/issues/43 - in that pull request i's even possible to run `make enable-service` (run just `make` for a full list of targets).

**Comment by tobixen** [comment]
I also run aw-watcher-network.service and aw-watcher-afk-prompt.service - for the network watcher the service file is available as a pull request - https://github.com/ActivityWatch/aw-watcher-network/pull/10

It may be tricky to give the services access to the wayland session (needed by aw-watcher-window-wayland and aw-watcher-afk-prompt) - I have to expose the `WAYLAND_DISPLAY` by doing `systemctl --user import-environment WAYLAND_DISPLAY`.  (This variable is typically `wayland-1` or `wayland-0`, so I could have added a fallback for guessing/detecting the variable if it's not given).
