### ISSUE TITLE
Questions on Debian Packaging Defaults for ActivityWatch + awatcher Bundle

### ISSUE THREAD

**Issue by philippedev101** [ActivityWatch/activitywatch#1146]
Hi,

i'm working on a Debian package for Ubuntu 24.04 that bundles `activitywatch` (core, rust server, qt), `awatcher` (rust), and `focused-window-dbus`. My goal is a good out-of-the-box experience. I have a few questions about how `aw-qt` and `aw-server-rust` handle defaults, which impacts packaging. I used the latest commit for all packages.

1.  API Browser Link: When i click "Open API browser" in `aw-qt`, it goes to `http://localhost:5600/api`, which gives a 404. The server log says "No matching routes for GET /api text/html." Specific endpoints like `/api/0/info` work fine. Is the `/api` link in `aw-qt` configurable, or is there an expectation that `/api` itself should serve something?

2.  Tray Icon Path: `aw-qt` shows a clickable area in the system tray, but no visible icon. My package installs icons to `/usr/share/icons/hicolor/` and the `.desktop` file specifies `Icon=activitywatch`. `strace` suggests `aw-qt` might be looking for icon files in paths relative to where it was run (like `icons:logo.png` or `media/application_exit.png`) instead of just using the system theme. Where does `aw-qt` expect to find its tray icon?

3.  Desktop Launcher Icon Size: The launcher icon for `aw-qt` appears very small. I'm installing SVG and various PNG sizes (512, 128, and planning to add 256, 64, 48 from SVG). The ActivityWatch project has its own `.deb` build. Do you have advice on how you get full-sized launcher icons to display reliably from your `.desktop` file?

4.  `aw-qt.toml` Configuration Path: `aw-qt` seems to only look for `~/.config/activitywatch/aw-qt/aw-qt.toml`. If it's not there, it uses internal defaults (which try to start Python watchers that fail on Wayland) and creates a new user config. It doesn't seem to use a system-wide default like `/etc/xdg/activitywatch/aw-qt/aw-qt.toml` as a fallback. This makes it hard to ship a package where `aw-qt` uses our preferred settings (e.g., to start `aw-awatcher` instead of the Python watchers) without user action after install. Does `aw-qt` check any other system-wide paths for `aw-qt.toml` if the user's file is missing? Or is the current behavior intended?

5.  Systemd Service for `aw-server-rust`: My package runs `aw-server-rust` as a systemd user service (`activitywatch-server.service`), which users enable. Do you have any recommendations or concerns about this approach for the server? Is a systemd service generally a good idea for `aw-server-rust`?

Thanks for any help or pointers on these.

**Comment by ErikBjare** [comment]
Sorry I completely missed this very thoughtful question.

Do you still need help with these? Happy to provide pointers.

I can quickly say that

(1) API browser not available with aw-server-rust
(2) I think icons get bundled into a QtResource? or handled in the pyinstaller `.spec`? you'll need to check aw-qt source
(3) sorry no, it has just worked for me with the pngs (SVG requires a non-standard font Varela Round)
(4) that seems like it should be fixed
(5) That's fine, and makes sense that users can *choose* to enable it as a service, but I think most should just use `aw-qt`, since its needed for watchers anyway (needs `DISPLAY` for window watchers under X11 etc).

**Comment by TimeToBuildBob** [comment]
Hi @philippedev101,

I investigated the icon handling that Erik mentioned. Here's what I found by examining the source:

## Tray Icon Path Details (Question 2)

The tray icon issue you're experiencing is because **aw-qt uses relative paths from the script location**, not system theme icons.

### How aw-qt Loads Icons

From `aw-qt/trayicon.py` (lines 205-216):

```python
scriptdir = Path(__file__).parent

# Adds search path relative to script location
QtCore.QDir.addSearchPath("icons", str(scriptdir.parent / "media/logo/"))

# Then loads icons with:
icon = QIcon("icons:logo.png")  # Uses the custom search path
```

### PyInstaller Bundling

From `aw-qt/aw-qt.spec` (line 22):
```python
datas=[('resources/aw-qt.desktop', '.'), ('media', 'media')]
```

The entire `media` directory is bundled relative to the executable, which is why PyInstaller builds work.

### Why Your Approach Doesn't Work

Installing icons to `/usr/share/icons/hicolor/` (standard FHS location) works for:
- ✓ Desktop launchers (reads from .desktop file's `Icon=activitywatch`)
- ✗ Tray icon code (expects `media/logo/` relative to script)

The strace output you saw (`icons:logo.png`, `media/application_exit.png`) confirms aw-qt is looking for **relative paths**, not system theme icons.

### Solutions for Debian Packaging

**Option 1: Install media files relative to script** (recommended)
```bash
# If aw-qt installed to /usr/bin/aw-qt
# Install media to /usr/share/activitywatch/media/
# Then patch or symlink so relative path works
```

**Option 2: Patch trayicon.py**
Add system-wide search path:
```python
# After line 216 in trayicon.py, add:
QtCore.QDir.addSearchPath("icons", "/usr/share/activitywatch/media/logo/")
```

**Option 3: Wrapper script**
Create wrapper that ensures correct paths before launching aw-qt.

### Upstream Consideration

This relative path dependency makes system-wide installation challenging. Consider opening an issue upstream to support XDG base directories (`$XDG_DATA_DIRS`) for system-wide installations.

Hope this helps with your packaging! Let me know if you need clarification on any of these approaches.

**Comment by philippedev101** [comment]
Hello!

thanks for the pointers. I wanted to make a deb with the rust server component and everything working so it can be easily installed on ubuntu for personal use. I was considering releasing the deb build scripts once i had everything working. At the moment i can't attend to this side project, but your comments are not wasted as i think the issues are still there to deal with.

**Comment by ErikBjare** [comment]
No worries, thanks for doing the work! Happy to review the deb build scripts you did write, even if they are not ready for prime time :)
