### ISSUE TITLE
100 % CPU usage after re-login

### ISSUE THREAD

**Issue by datalot-369** [ActivityWatch/activitywatch#486]
- [x] I am on the [latest](https://github.com/ActivityWatch/activitywatch/releases/latest) ActivityWatch version.
 - [x] I have searched the issues of this repo and believe that this is not a duplicate.

- **OS version and name**: `MX Linux 19.2 amd64` /  `XFCE 4.14 LightDM` / `GTK+ Greeter`
- **ActivityWatch version**: `0.9.2`

## Describe the bug

If I restart my computer, login, logout, and re-login, the Activity Watch process freezes consuming 100 % of single CPU core. 

## To Reproduce
    1. Set ActivityWatch to start at login in `Session and Startup`.
    2. Reboot.
    3. Login.
    4. Wait until all is loaded, you will note AW is working properly.
    5. Logout.
    6. Login again. Now one of your CPU cores will be used at 100 % until you kill the process.

## Expected behavior

ActivityWatch process should terminate and start as the first login.  
Maybe there are unsuccessful process termination that conflict in the re-login.

## Documentation

[logs.zip](https://github.com/ActivityWatch/activitywatch/files/5307633/logs.zip)

**Comment by ErikBjare** [comment]
ActivityWatch starts several processes, which process exactly takes up 100% CPU?

**Comment by ErikBjare** [comment]
Related to https://github.com/ActivityWatch/aw-qt/issues/49

The underlying issue is probably still a tight loop somewhere, so exactly which process is maxing out CPU would still be useful.

**Comment by TornaxO7** [comment]
@ErikBjare Suddenly I have a CPU usage of 100% as well on one core. But in my case, I just killed the xorg server and started it again, than the `aw-watcher-window` started to comsumpt always 100% of the CPU.

**Comment by TornaxO7** [comment]
![image](https://user-images.githubusercontent.com/50843046/116793861-9cc16300-aac9-11eb-818e-85e671b28cea.png)

Here's an image if it helps you.

**Comment by ErikBjare** [comment]
I checked aw-watcher-window and can't find any signs of a tight loop being ran. 

I tested it with a virtual xserver (Xvfb) using the following and managed to reproduce the errors that occur if the xserver disappears:

```sh
Xvfb :10 &
export DISPLAY=:10
aw-watcher-window --testing
kill Xvfb
```

However, no 100% CPU, so I'm assuming this has been fixed.

If the issue appears again, please let me know! (just let me know which process)

**Comment by qcol** [comment]
![2023-07-06_09-58](https://github.com/ActivityWatch/activitywatch/assets/358993/862c2c15-9657-4c69-a237-800f51ff1e5c)

I think this problem still exists. Often when I hear loud fans, I check htop and there Activitywath CPU 100%.   I think the rule here is waking up the laptop from sleep, that's when I mostly observe this problem. Restarting the activitywatch process helps. 

Version:  v0.12.2 (rust)
Ubuntu 22.04.2 LTS
