### ISSUE TITLE
Edge browser plugin not showing in activity

### ISSUE THREAD

**Issue by las-nsc** [ActivityWatch/activitywatch#516]
Data is recorded and shown in the timeline, but I can't use the URL to filter browser usage between activities and nothing is displayed under the 'browser' tab.

AW Version: 0.9.2
Installed edge plugin from the chrome web store.

**Comment by las-nsc** [comment]
I came from the link in the web UI and it didn't show me the template. When I went to add another did then show it, but there's so much to fill in it put me off filling it in.

**Comment by ErikBjare** [comment]
>I can't use the URL to filter browser usage between activities

Known issue, see https://github.com/ActivityWatch/activitywatch/issues/352.

>nothing is displayed under the 'browser' tab.

Known issue (https://github.com/ActivityWatch/activitywatch/issues/399), however, it should have been fixed in v0.10.0 that was just released.

>I came from the link in the web UI and it didn't show me the template.

Ah, that's good to know! I'll look into fixing that.

>but there's so much to fill in it put me off filling it in.

The point is to save us (the devs) time. If people don't to fill it, then it's a lot harder for us to figure out what went wrong (and if you'd have followed it, you'd have found the other issues that this is a duplicate of :wink:).

**Comment by las-nsc** [comment]
I just updated to 10.0 and nothing has changed (issue link doesn't use the template either).

**Comment by ErikBjare** [comment]
@las-nsc Make sure you hard-refresh the page (it should have a 'New view' button, for example), and if that doesn't work, create a new issue following the template.

The issue template link was fixed in https://github.com/ActivityWatch/aw-webui/commit/0ba820dcedafbe8829cab0190d50d89810dabcc1, and will be in the next release.

**Comment by las-nsc** [comment]
Also:
- URL filtering I didn't look for, but was secondary to the issue of not seeing the activity in the browser tab.
- I searched for edge before posting and found no open issues. Bad timing that you happened to do a release the day I decided to post the issue. The issue is closed, but I'm still seeing the same thing in 0.10.0. Do I need a plugin update too?

**Comment by ErikBjare** [comment]
>I searched for edge before posting and found no open issues

I guess we should make it clear to people to search closed issues too, good point!

>The issue is closed, but I'm still seeing the same thing in 0.10.0.

I just tested Edge on Windows myself and it works for me in v0.10.

>Do I need a plugin update too?

That should not be necessary.

**Comment by ErikBjare** [comment]
>UPDATE: I can see the activity now, I had to do a number of hard and soft refreshes, and navigating away to get it to show though. I hadn't left the tab open, while installing and all processes were killed so I find it odd that it would be cached as it seemed to be.

Yeah, the browser caching is weird on updates. I'll look into that, sorry for the confusion!

**Comment by las-nsc** [comment]
Ok, all good then. Just need those URL filters. I'll fill out a separate bug about another issue (if it's not already logged). Cheers.

**Comment by Doslin** [comment]
I encountered the same problem. Uninstalling the browser plugin twice on edge or Chrome doesn't work. What should I do next to fix it?
Can someone help me? I would greatly appreciate it.

![image](https://github.com/ActivityWatch/activitywatch/assets/29807388/fc487f74-cf98-41c5-80b1-03e09685629e)
![image](https://github.com/ActivityWatch/activitywatch/assets/29807388/bb5d0b26-4382-49bf-bb80-e116973adafb)
